name: ${{'Upload Multiple Files Example'}}
 

on:
  workflow_dispatch:
    inputs:
      deploy env:
        description: 'Environment to deploy to'
        required: true

jobs:
  upload-files:
    runs-on: ubuntu-latest

    steps:
      - name: Grouping
        run: |
          echo ::group :: Uploading files
          echo "This is a group of steps"
          echo "This is a group of steps"
          echo ::endgroup ::

      - name: Checkout code
        run: echo "$INPUT_DEPLOY_ENV"
