name: New Workflow

on: 
    workflow_dispatch:
 

jobs:
    running_job:
        runs-on: ubuntu-latest
        steps:
        - name: Print shell
          run: |
            echo index.js
            echo "Deployment complete ✅"
        - name: Print another
          run: echo Lord  
        - name: conditional
          if: github.ref_name == 'main'
          run: echo Main branch building
        - name: conditional
          if: github.ref_name == 'master'
          run: echo Master branch building