name: Create GitHub Release

on:
  push:
  workflow_dispatch:
    

jobs:
  release:
    name: Release Component
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: ./index.js

