name: New Workflow

on: 
    gollum:
    pull_request:
    fork:
    issue_comment:
        types: [created, deleted]
 

jobs:
    running_job:
        runs-on: ubuntu-latest
        steps:
        - name: Print shell
          run: |
            echo index.js
            echo "Deployment complete ✅"
        - name: Print another
          run: echo Lord  
        