name: New Workflow

on: 
    gollum:
    pull_request:
    fork:
    issue_comment:
        types: [created, deleted]
    workflow_dispatch:
    schedule:
        - cron: "*/2 * * * *"

jobs:
    running_job:
        runs-on: ubuntu-latest
        steps:
        - name: Print shell
          run: echo index.js
        