name: Upload Multiple Files Example

on:
  push:
    branches:
      - main

jobs:
  upload-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Upload all text files from the repo
        uses: actions/upload-artifact@v3
        with:
          name: text-files-artifact  # Artifact name
          path: '**/*.js'  # Wildcard pattern to match all .txt files
