name: Upload Multiple Files Example
 

on:
  workflow_dispatch:
    inputs:
      deploy env:
        description: 'Environment to deploy to'
        required: true

jobs:
  upload-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: echo ${ DEPLOY_ENV }
